name: Setup AWS

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    name: Setup via Terraform
    runs-on: ubuntu-latest
    environment: test

    steps:
    - name: Checkout
      uses: actions/checkout@v3
