name: Vinces Videos - Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore Api Dependencies
      run: dotnet restore Api/
    - name: Restore Unit Test Dependencies
      run: dotnet restore Api.Tests/
    - name: Build
      run: dotnet build Api/ --no-restore
    - name: Test Api
      run: dotnet test Api/ --no-build --verbosity normal
    - name: Build Unit Tests
      run: dotnet build Api.Tests/ --no-restore
    - name: Run Unit Tests
      run: dotnet test Api.Tests/ --no-build --verbosity normal
